# Generated by Django 3.2.9 on 2021-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khóa học')),
                ('ctype', models.CharField(max_length=50, verbose_name='Loại khóa học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('status', models.CharField(choices=[('opening', 'Đang mở để đăng ký'), ('inprogress', 'Đang tiến hành'), ('ended', 'Đã kết thúc')], max_length=50, verbose_name='Trạng thái khóa học')),
                ('tuition_fee', models.FloatField(verbose_name='Học phí')),
                ('description', models.TextField(verbose_name='Mô tả khóa học')),
                ('schedule', models.TextField(verbose_name='Lịch trình')),
            ],
        ),
    ]
