# Generated by Django 3.2.9 on 2021-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(null=True, verbose_name='Link ảnh minh họa'),
        ),
    ]
