# Generated by Django 3.2.9 on 2021-12-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211206_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
