# Generated by Django 3.2.9 on 2021-12-12 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursestudents_courseteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudents',
            name='score',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Điểm tổng kết'),
        ),
    ]
