# Generated by Django 3.2.9 on 2021-11-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_schelude_course_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
